### ISSUE TITLE
Sidebar: Make 'Risk of Bias' the list subheading & rename

### ISSUE THREAD

**Issue by ninadicara** [DynamicGenetics/Covid-Communities-Map#15]
'Risk of Bias' is currently the first subheading on the map. We would like it to appear last.

In the process, it should also be renamed from 'Risk of Bias' to 'Factors Affecting Data Quality'

**Comment by CMorenoStokoe** [comment]
fixed as of merge 1:57 pm 20/4/20

**Comment by CMorenoStokoe** [comment]
4
