### ISSUE TITLE
Data is not all scaled in the same direction

### ISSUE THREAD

**Issue by ninadicara** [DynamicGenetics/Covid-Communities-Map#18]
Data (e.g. `COVID Vulnerable (comborbidity %)`) is not all scaled in the same direction, or to the same scale. 
This needs to be addressed for the interpretability of the map.

**Comment by CMorenoStokoe** [comment]
This is fixable simply by enabling 'reverseColors' in the dataSources.py. I am doing this and closing this issue

**Comment by CMorenoStokoe** [comment]
However, I am opening a new issue for data scale, since this is a separate issue with a separate solution
