### ISSUE TITLE
better on hover data readout

### ISSUE THREAD

**Issue by CMorenoStokoe** [DynamicGenetics/Covid-Communities-Map#5]
Changelog:
- add units to on hover data
- consider renaming layers to shorter names on on:hover readout
- build dictionary for these units & short names
- revise number formatting (e.g., so there aren't 0.000 values)

**Comment by leriomaggio** [comment]
In addition to that, when you hover on a LA, I would show the detail statistics for **all** the checkbox ticked rather than only the last one?

**Comment by ninadicara** [comment]
Closed and moved to 'Enhancements' section of project workflow board.
