### ISSUE TITLE
move bias to new map

### ISSUE THREAD

**Issue by CMorenoStokoe** [DynamicGenetics/Covid-Communities-Map#7]
Changelog:
- consider whether bias should exist on a different map or could be a different map view on the same page / layer
- consider what risk of bias means (e.g., rename to factors affecting data quality)
- implement new bias map mode/view/page

**Comment by ninadicara** [comment]
Closed as decided to keep bias on the map for the moment, but to rename it. Can reopen or add to enhancements later if needed. 
Decision made by @OliverDavis in meeting on 20.04.2020.
