### ISSUE TITLE
fix scrolling issue

### ISSUE THREAD

**Issue by CMorenoStokoe** [DynamicGenetics/Covid-Communities-Map#8]
Changelog:
- scrolling moves the whole page (source: Nina)
- sidebar size overflows page (source: Nina)

**Comment by ninadicara** [comment]
Hotfix by adding `overflow: scroll` to the sidebar CSS. May still want to consider the general layout of the sidebar, but this is a bigger task related to the data and layer choices that will need to be made later. 

[See commit here. ](https://github.com/DynamicGenetics/Covid-Communities-Map/commit/e4b22684d18206aa20d7716e3f9299cd36ed8f88)
